apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: {{ include "kafka-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-mcp.labels" . | nindent 4 }}
spec:
  description: kafka MCP server
  protocol: STREAMABLE_HTTP
  sseReadTimeout: 5m0s
  terminateOnClose: true
  timeout: 30s
  url: {{ include "kafka-mcp.serverUrl" . }}
