storageClasses:
- name: efs-sc
  annotations:
    # Use that annotation if you want this to your default storageclass
    storageclass.kubernetes.io/is-default-class: "true"
  parameters:
    provisioningMode: efs-ap
    fileSystemId: fs-093a1db32153f8479
    directoryPerms: "700"
    gidRangeStart: "1000"
    gidRangeEnd: "2000"
    basePath: "/dynamic_provisioning"
    subPathPattern: "/subPath"
    ensureUniqueDirectory: "true"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
controller:
  serviceAccount:
    create: false
    name: efs-csi-controller-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::941284018955:role/efscontroller
