apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb-mcp.labels" . | nindent 4 }}
data:
  MDB_MCP_CONNECTION_STRING: {{ .Values.mongodb.url }}
  DO_NOT_TRACK: "1"
  # Custom configuration
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
