apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongodb.serviceAccountToken }}
  ZIBI: {{ .Values.mongodb.serviceAccountToken | b64enc }}
  {{- end }}
 
