apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
  name: tic-automode
  region: il-central-1
  version: "1.32"
 
vpc:
  id: "vpc-0e439b2d301aaad81"
  subnets:
    private:
      il-central-1a:
        id: "subnet-08bc4d421b397a594"
      il-central-1b:
        id: "subnet-0f6d44ce6c4818cf0"
  clusterEndpoints:
    privateAccess: true
    publicAccess: false   # <â€” disables the public endpoint
 
autoModeConfig:
  enabled: true      