# In order to make sure the changes reach elasticsearch:
#   1. create a new json
#   2. add it to runPostInstall.sh
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-configuration
  # namespace: logging 
data:
  runPostInstall.sh: |-
{{ .Files.Get "elasticSearchConfFiles/runPostInstall.sh" | indent 4 }}

  elasticSearchParameter1.json: |-
{{ .Files.Get "elasticSearchConfFiles/elasticSearchParameter1.json" | indent 4 }}

  elasticSearchParameter2.json: |-
{{ .Files.Get "elasticSearchConfFiles/elasticSearchParameter2.json" | indent 4 }}

  tsgs-policy-delete.json: |-
{{ .Files.Get "elasticSearchConfFiles/tsgs-policy-delete.json" | indent 4 }}

  app-nologformat-write.json: |-
{{ .Files.Get "elasticSearchConfFiles/app-nologformat-write.json" | indent 4 }}

  elastic-test.json: |-
{{ .Files.Get "elasticSearchConfFiles/elastic-test.json" | indent 4 }}

  app-write.json: |-
{{ .Files.Get "elasticSearchConfFiles/app-write.json" | indent 4 }}

  reality-history.json: |-
{{ .Files.Get "elasticSearchConfFiles/reality-history.json" | indent 4 }}
    
  add-timestamp-to-reality.json: |-
{{ .Files.Get "elasticSearchConfFiles/add-timestamp-to-reality.json" | indent 4 }}

  structured-metadata-format.json: |-
{{ .Files.Get "elasticSearchConfFiles/structured-metadata-format.json" | indent 4 }}
  
  app-adlg-write.json: |-
{{ .Files.Get "elasticSearchConfFiles/app-adlg-write.json" | indent 4 }}

  tsgs-app-write-policy-delete.json: |-
{{ .Files.Get "elasticSearchConfFiles/tsgs-app-write-policy-delete.json" | indent 4 }}

  tsgs-history-policy-delete.json: |-
{{ .Files.Get "elasticSearchConfFiles/tsgs-history-policy-delete.json" | indent 4 }}

  test-policy-delete.json: |-
{{ .Files.Get "elasticSearchConfFiles/test-policy-delete.json" | indent 4 }}
