driver:
  enabled: false
validator:
  repository: 941284018955.dkr.ecr.il-central-1.amazonaws.com/nvidia
  image: gpu-operator
operator:
  repository: 941284018955.dkr.ecr.il-central-1.amazonaws.com/nvidia
  image: gpu-operator

dcgmExporter:
  enabled: false

toolkit:
  enabled: true
  repository: 941284018955.dkr.ecr.il-central-1.amazonaws.com/nvidia/k8s
  image: container-toolkit