image:
  registry: docker.io
  repository: ronbutbul135/kafka-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

yamlApplicationConfig:
  # {}
  kafka:
    clusters:
      - name: ticipici-bitnami-new
        bootstrapServers: bitnami-kafka-controller-headless:9092
  spring:
    security:
      oauth2:
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  ingressClassName: "nginx"
  path: "/"
  pathType: "Prefix"
  host: "kafkaui.testmpr.aws2.rafael.co.il"
  tls:
    enabled: true
    secretName: "testmpr-aws-wildcard-cert"
