

yamlApplicationConfig:
  # {}
  kafka:
    clusters:
      - name: ticipici-bitnami-new
        bootstrapServers: bitnami-kafka-controller-headless:9092
  spring:
    security:
      oauth2:
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  apiVersion: ~
  path: "/"
  pathType: "Prefix"
  host: "kafkaui.mprtest.aws2.rafael.co.il"
  tls:
    enabled: true
    secretName: "testmpr-aws-wildcard-cert"
