registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
querydoc:
  replicas: 1
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
controller:
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
