registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
querydoc:
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
controller:
  agentImage:    
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"    
ui:
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
kmcp:
  image:
    repository: 941284018955.dkr.ecr.il-central-1.amazonaws.com/kagent-dev/kmcp/controller
kagent-tools:
  tools:
    image:
      registry: 941284018955.dkr.ecr.il-central-1.amazonaws.com
agents:
  cilium-policy-agent:
    enabled: false
  cilium-manager-agent:
    enabled: false
  cilium-debug-agent:
    enabled: false
  helm-agent:
    enabled: false
  istio-agent:
    enabled: false
  kgateway-agent:
    enabled: false
  observability-agent:
    enabled: false
  promql-agent:
    enabled: false
