registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
querydoc:
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
controller:
  agentImage:    
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"    
ui:
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
kmcp:
  image:
    repository: 941284018955.dkr.ecr.il-central-1.amazonaws.com/kagent-dev/kmcp/controller
kagent-tools:
  tools:
    image:
      registry: 941284018955.dkr.ecr.il-central-1.amazonaws.com

k8s-agent:
  modelConfigRef: "vllm-gpt"

mongodb-mcp:
  mongodb:
    url: "mongodb://mongo8-primary:27017"
grafana-mcp:
  grafana:
    url: "grafana.kagent:3000/api"
    serviceAccountToken: ""
    apiKey: "" # Deprecated - use serviceAccountToken instead.

kafka-mcp:
  kafka:
    url: "bitnami-kafka:9092"
  kafkaadmin:
    url: "bitnami-kafka-controller-headless:9093"
agents:
  cilium-policy-agent:
    enabled: false
  cilium-manager-agent:
    enabled: false
  cilium-debug-agent:
    enabled: false
  helm-agent:
    enabled: false
  istio-agent:
    enabled: false
  kgateway-agent:
    enabled: false
  observability-agent:
    enabled: false
  promql-agent:
    enabled: false
  argo-rollouts-agent:
    enabled: false
    
