registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
querydoc:
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
controller:
  agentImage:    
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"    
ui:
  image:
    registry: "941284018955.dkr.ecr.il-central-1.amazonaws.com"
