image:
  repository: ghcr.io/open-webui/open-webui

ollama:
  enabled: false

ingress:
  enabled: true
  class: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  host: "openwebui.testmpr.aws2.rafael.co.il"
  tls: true
  existingSecret: "testmpr-aws-wildcard-cert"

