image:
  repository: 941284018955.dkr.ecr.il-central-1.amazonaws.com/open-webui/open-webui

ollama:
  enabled: false

ollamaUrls:
  - "http://vllm-llama3-engine-service/v1"

ingress:
  enabled: true
  class: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  host: "openwebui.testmpr.aws2.rafael.co.il"
  tls: true
  existingSecret: "testmpr-aws-wildcard-cert"

pipelines:
  enabled: false


websocket:
  redis:
    image:
      repository: 941284018955.dkr.ecr.il-central-1.amazonaws.com/redis