apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-service.fullname" . }}
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: websocket
    protocol: TCP
    name: websocket
  selector:
    {{- include "gateway-service.selectorLabels" . | nindent 4 }}

