annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 0.2.2
description: A Helm chart for KMCP (Kubernetes MCP Server Controller)
home: https://github.com/kagent-dev/kmcp
keywords:
- mcp
- kubernetes
- controller
- server
maintainers:
- email: maintainers@kagent.dev
  name: kmcp-maintainers
name: kmcp
sources:
- https://github.com/kagent-dev/kmcp
type: application
version: 0.2.2
