apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: {{ include "elasticsearch-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch-mcp.labels" . | nindent 4 }}
spec:
  description: elasticsearch MCP server
  protocol: STREAMABLE_HTTP
  sseReadTimeout: 5m0s
  terminateOnClose: true
  timeout: 30s
  url: {{ include "elasticsearch-mcp.serverUrl" . }}
